#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
import os

AUTHOR = u'John D. Griffiths'
SITENAME = u"JDG Lab Notebook"
SITEURL = 'https://johngriffiths.github.io/LabNotebook'
#SITESUBTITLE = u'Open Notebook Science.'


TIMEZONE = 'US/Pacific'

DEFAULT_LANG = u'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None

TAG_FEED_ATOM = "feeds/tag_%s.atom.xml"


MENUITEMS = [('About', 'https://johngriffiths.github.io/LabNotebook/about-the-notebook.html'),
             ('Archives', 'https://johngriffiths.github.io/LabNotebook/archives.html'),
             ('Github repo', 'https://github.com/JohnGriffiths/LabNotebook.html'),
	     ('Open Notebook Science', 'http://en.wikipedia.org/wiki/Open_notebook_science')]

#('Home Page', 'http://www.astro.washington.edu/users/vanderplas')]
NEWEST_FIRST_ARCHIVES = False


# Blogroll
#LINKS =  (('Lab notebook github repo', 'https://github.com/JohnGriffiths/LabNotebook'),
#	  ('JDG Website', 'http://johndavidgriffiths.strikingly.com'),
#	  ('JDG Blog', 'https://johngriffiths.github.io/neurodidact'),
#	  ('Open Notebook Science', 'http://en.wikipedia.org/wiki/Open_notebook_science'))

#          ('Python.org', 'http://python.org/'),
#          ('Jinja2', 'http://jinja.pocoo.org/'),
#          ('You can modify those links in your config file', '#'),)

# Social widget
#SOCIAL = (('You can add links in your config file', '#'),
#          ('Another social link', '#'),)

DEFAULT_PAGINATION = 1

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

#THEME='pelican-bootstrap3'

CODE_DIR = '../../resources/code' #'downloads/code'
NOTEBOOK_DIR = '../../resources/notebooks' # 'downloads/notebooks'

# Theme and plugins
#THEME = '../pelican-themes/cebong' # 'waterspill-en' # 'pelican-octopress-theme/'
#THEME = 'pelican-octopress-theme'
THEME = 'theme/labnotebook-pelican-octopress-theme'
PLUGIN_PATH = 'plugins/pelican-plugins'






# Sharing
#TWITTER_USER = 'neurodidact'
#GOOGLE_PLUS_USER = 'j.davidgriffiths'
#GOOGLE_PLUS_ONE = True
#GOOGLE_PLUS_HIDDEN = False
#FACEBOOK_LIKE = False
#TWITTER_TWEET_BUTTON = True
#TWITTER_LATEST_TWEETS = True
#TWITTER_FOLLOW_BUTTON = True
#TWITTER_TWEET_COUNT = 3
#TWITTER_SHOW_REPLIES = 'false'
#TWITTER_SHOW_FOLLOWER_COUNT = 'true'




# This requires Pelican 3.3+
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png']

#CODE_DIR = '../../resources/code'             # downloads/code
#NOTEBOOK_DIR = '../../resources/notebooks' # downloads/notebooks @'

#PLUGIN_PATH = 'pelican-plugins'
#PLUGIN_PATH='/media/sf_SharedFolder/Code/git_repos_of_others/PythonicPerambulations/pelican-plugins'

PLUGINS = ['summary', 'liquid_tags.img', 'liquid_tags.video'
                      'liquid_tags.include_code', 'liquid_tags.notebook',
		      'liquid_tags.literal',
	   'encrypt_content']


DISPLAY_PAGES_ON_MENU = False


# The theme file should be updated so that the base header contains the line:
#
#  {% if EXTRA_HEADER %}
#    {{ EXTRA_HEADER }}
#  {% endif %}
# 


# This header file is automatically generated by the notebook plugin
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found.  "
			                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')


# Search
SEARCH_BOX = True

